In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
import seaborn
seaborn.set()
from sklearn.linear_model import LinearRegression

In [14]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [32]:
google_drive_csv_path = '/content/drive/My Drive/MESA/AI/Veritus/Staff Survey_anonymized.csv'
drive_df = pd.read_csv(google_drive_csv_path)
drive_df.head(5)

,StartDate,EndDate,Progress,Duration (in seconds),Finished,RecordedDate,Q2.2_1,Q2.2_2,Q2.2_3,Q2.2_4,...,Q5.2_3,Q5.2_4,Q5.2_5,Q5.2_6,Q5.2_7,Q5.2_8,Q5.2_9,Q5.3,Q5.4,Q5.5
0,Start Date,End Date,Progress,Duration (in seconds),Finished,Recorded Date,How important are the following aspects for pr...,How important are the following aspects for pr...,How important are the following aspects for pr...,How important are the following aspects for pr...,...,How important should each of the following ide...,How important should each of the following ide...,How important should each of the following ide...,How important should each of the following ide...,How important should each of the following ide...,How important should each of the following ide...,How important should each of the following ide...,Are there any other ideas or priorities you be...,"As you look ahead, how can Augustin College be...","Looking forward, how can Augustin College cult..."
1,"{""ImportId"":""startDate"",""timeZone"":""America/Ne...","{""ImportId"":""endDate"",""timeZone"":""America/New_...","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""America...","{""ImportId"":""QID21_1""}","{""ImportId"":""QID21_2""}","{""ImportId"":""QID21_3""}","{""ImportId"":""QID21_4""}",...,"{""ImportId"":""QID39_3""}","{""ImportId"":""QID39_4""}","{""ImportId"":""QID39_5""}","{""ImportId"":""QID39_6""}","{""ImportId"":""QID39_7""}","{""ImportId"":""QID39_8""}","{""ImportId"":""QID39_9""}","{""ImportId"":""QID40_TEXT""}","{""ImportId"":""QID46_TEXT""}","{""ImportId"":""QID47_TEXT""}"
2,5/15/2025 16:41,5/15/2025 16:42,100,33,TRUE,5/15/2025 16:42,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5/16/2025 12:06,5/16/2025 12:54,100,2896,TRUE,5/16/2025 12:54,Extremely important,Extremely important,Extremely important,Moderately Important,...,Moderately important,Extremely important,Extremely important,Moderately important,Very important,Moderately important,Extremely important,NaN,NaN,NaN
4,5/16/2025 12:52,5/16/2025 13:01,100,538,TRUE,5/16/2025 13:01,Extremely important,Extremely important,Extremely important,Very important,...,Extremely important,Extremely important,Extremely important,Extremely important,Very important,Extremely important,Extremely important,NaN,Increase emphasis on policy and procedure inte...,Streamline communication with all staff member...

In [35]:
drive_df.info()
drive_df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 100 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   StartDate              22 non-null     object
 1   EndDate                22 non-null     object
 2   Progress               22 non-null     object
 3   Duration (in seconds)  22 non-null     object
 4   Finished               22 non-null     object
 5   RecordedDate           22 non-null     object
 6   Q2.2_1                 17 non-null     object
 7   Q2.2_2                 17 non-null     object
 8   Q2.2_3                 17 non-null     object
 9   Q2.2_4                 17 non-null     object
 10  Q2.2_5                 17 non-null     object
 11  Q2.2_6                 17 non-null     object
 12  Q2.2_7                 17 non-null     object
 13  Q2.2_8                 17 non-null     object
 14  Q2.3_1                 16 non-null     object
 15  Q2.3_4                 16 non-null     object
 16  Q2.3_5                 16 non-null     object
 17  Q2.3_6                 16 non-null     object
 18  Q2.3_7                 16 non-null     object
 19  Q2.3_8                 16 non-null     object
 20  Q2.3_9                 16 non-null     object
 21  Q2.4_1                 15 non-null     object
 22  Q2.4_2                 15 non-null     object
 23  Q2.4_3                 15 non-null     object
 24  Q2.4_4                 15 non-null     object
 25  Q3.2_1                 17 non-null     object
 26  Q3.2_2                 17 non-null     object
 27  Q3.2_3                 17 non-null     object
 28  Q3.2_4                 17 non-null     object
 29  Q3.2_5                 17 non-null     object
 30  Q3.2_6                 17 non-null     object
 31  Q3.2_7                 17 non-null     object
 32  Q3.3_1                 17 non-null     object
 33  Q3.3_2                 17 non-null     object
 34  Q3.3_3                 17 non-null     object
 35  Q3.4_1                 17 non-null     object
 36  Q3.4_2                 17 non-null     object
 37  Q3.4_3                 17 non-null     object
 38  Q3.4_4                 17 non-null     object
 39  Q3.5_1                 17 non-null     object
 40  Q3.5_2                 17 non-null     object
 41  Q3.5_3                 17 non-null     object
 42  Q3.5_4                 17 non-null     object
 43  Q3.5_5                 17 non-null     object
 44  Q3.6_1                 17 non-null     object
 45  Q3.6_2                 17 non-null     object
 46  Q3.6_3                 17 non-null     object
 47  Q3.6_4                 17 non-null     object
 48  Q3.6_5                 17 non-null     object
 49  Q3.7_1                 17 non-null     object
 50  Q3.7_2                 17 non-null     object
 51  Q3.7_3                 17 non-null     object
 52  Q3.7_4                 17 non-null     object
 53  Q3.7_5                 17 non-null     object
 54  Q3.8                   12 non-null     object
 55  Q4.2_1                 16 non-null     object
 56  Q4.2_2                 16 non-null     object
 57  Q4.2_3                 16 non-null     object
 58  Q4.2_4                 16 non-null     object
 59  Q4.3_1                 16 non-null     object
 60  Q4.3_2                 16 non-null     object
 61  Q4.3_3                 16 non-null     object
 62  Q4.4_1                 15 non-null     object
 63  Q4.4_2                 15 non-null     object
 64  Q4.4_3                 15 non-null     object
 65  Q4.4_4                 15 non-null     object
 66  Q4.4_5                 15 non-null     object
 67  Q4.4_6                 15 non-null     object
 68  Q4.4_7                 15 non-null     object
 69  Q4.4_8                 15 non-null     object
 70  Q4.4_9                 15 non-null     object
 71  Q4.4_10                15 non-null     object
 72  Q4.4_11                15 non-null     object
 73  Q4.4_12                15 non-null     object
 74  Q4.4_13                15 non-null     object
 75  Q4.4_14                15 non-null     object
 76  Q4.5_1                 16 non-null     object
 77  Q4.5_2                 16 non-null     object
 78  Q4.5_3                 16 non-null     object
 79  Q4.6_1                 15 non-null     object
 80  Q4.6_2                 16 non-null     object
 81  Q4.6_3                 16 non-null     object
 82  Q4.6_4                 16 non-null     object
 83  Q4.6_5                 16 non-null     object
 84  Q4.6_6                 16 non-null     object
 85  Q4.6_7                 16 non-null     object
 86  Q4.6_8                 16 non-null     object
 87  Q4.7                   10 non-null     object
 88  Q5.2_1                 16 non-null     object
 89  Q5.2_2                 16 non-null     object
 90  Q5.2_3                 16 non-null     object
 91  Q5.2_4                 16 non-null     object
 92  Q5.2_5                 16 non-null     object
 93  Q5.2_6                 16 non-null     object
 94  Q5.2_7                 16 non-null     object
 95  Q5.2_8                 16 non-null     object
 96  Q5.2_9                 16 non-null     object
 97  Q5.3                   9 non-null      object
 98  Q5.4                   12 non-null     object
 99  Q5.5                   11 non-null     object
dtypes: object(100)
memory usage: 17.3+ KB

(22, 100)

In [33]:
drive_df.drop([0,1])

,StartDate,EndDate,Progress,Duration (in seconds),Finished,RecordedDate,Q2.2_1,Q2.2_2,Q2.2_3,Q2.2_4,...,Q5.2_3,Q5.2_4,Q5.2_5,Q5.2_6,Q5.2_7,Q5.2_8,Q5.2_9,Q5.3,Q5.4,Q5.5
2,5/15/2025 16:41,5/15/2025 16:42,100,33,TRUE,5/15/2025 16:42,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5/16/2025 12:06,5/16/2025 12:54,100,2896,TRUE,5/16/2025 12:54,Extremely important,Extremely important,Extremely important,Moderately Important,...,Moderately important,Extremely important,Extremely important,Moderately important,Very important,Moderately important,Extremely important,NaN,NaN,NaN
4,5/16/2025 12:52,5/16/2025 13:01,100,538,TRUE,5/16/2025 13:01,Extremely important,Extremely important,Extremely important,Very important,...,Extremely important,Extremely important,Extremely important,Extremely important,Very important,Extremely important,Extremely important,NaN,Increase emphasis on policy and procedure inte...,Streamline communication with all staff member...
5,5/16/2025 12:35,5/16/2025 13:08,100,2001,TRUE,5/16/2025 13:08,Extremely important,Extremely important,Extremely important,Extremely important,...,Extremely important,Extremely important,Extremely important,Very important,Extremely important,Extremely important,Very important,More hands-on opportunities for community enga...,"Please continue the good transparency, communi...",I think we should continue doing the kinds of ...
6,5/16/2025 14:47,5/16/2025 14:56,52,545,FALSE,5/16/2025 18:56,Extremely important,Extremely important,Extremely important,Extremely important,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,5/16/2025 21:42,5/16/2025 21:57,100,883,TRUE,5/16/2025 21:57,Extremely important,Very important,Extremely important,Very important,...,Extremely important,Extremely important,Extremely important,Extremely important,Extremely important,Extremely important,Extremely important,Access to mental health services,Training/Seminars,Work-pace Retreats
8,5/20/2025 8:47,5/20/2025 8:52,100,308,TRUE,5/20/2025 8:52,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,5/20/2025 9:37,5/20/2025 10:27,100,3030,TRUE,5/20/2025 10:27,Extremely important,Extremely important,Extremely important,Moderately Important,...,Extremely important,Very important,Very important,Moderately important,Very important,Extremely important,Very important,A key piece of supporting our students also in...,As Augustin College grows I think it's importa...,I think a lot of strides have already been mad...
10,5/20/2025 8:46,5/20/2025 8:46,4,4,FALSE,5/20/2025 12:46,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,5/22/2025 16:44,5/22/2025 16:57,100,746,TRUE,5/22/2025 16:57,Extremely important,Extremely important,Extremely important,Extremely important,...,Extremely important,Extremely important,Extremely important,Extremely important,Extremely important,Very important,Very important,"As the world grows more complicated, develop a...",Opportunities to work with other schools acros...,Cross department work experiences.
12,5/22/2025 21:56,5/22/2025 21:59,100,173,TRUE,5/22/2025 21:59,Very important,Very important,Very important,Very important,...,Very important,Extremely important,Extremely important,Very important,Extremely important,Very important,Extremely important,NaN,NaN,NaN
13,5/23/2025 8:42,5/23/2025 8:59,100,1042,TRUE,5/23/2025 8:59,Very important,Very important,Very important,Very important,...,Very important,Extremely important,Very important,Very important,Moderately important,Moderately important,Very important,Clear operational procedures so that programmi...,So far Augustin College has been very supportive.,I think it would be good to highlight differen...
14,5/23/2025 9:26,5/23/2025 9:37,100,651,TRUE,5/23/2025 9:37,Extremely important,Extremely important,Extremely important,Extremely important,...,Very important,Very important,Very important,Very important,Very important,Very important,Very important,Making stronger connections to Veritus Imperia...,Providing training and collaboration with othe...,Doing team building events
15,5/23/2025 13:06,5/23/2025 13:10,100,212,TRUE,5/23/2025 13:10,Extremely important,Extremely important,Extremely important,Extremely important,...,Extremely important,Extremely important,Extremely important,Extremely important,Extremely important,Extremely important,Very important,NaN,NaN,NaN
16,5/26/2025 11:54,5/26/2025 13:03,100,4119,TRUE,5/26/2025 13:03,Very important,Very important,Very important,Very important,...,Very important,Very important,Very important,Very important,Moderately important,Very important,Very important,NaN,acquiring better technology to perform daily d...,NaN
17,5/27/2025 16:33,5/27/2025 17:28,100,3262,TRUE,5/27/2025 17:28,Very important,Very important,Extremely important,Moderately Important,...,Very important,Extremely important,Very important,Moderately important,Extremely important,Extremely important,Very important,NaN,More opportunities for professional advancement,Building stronger bridges between departments
18,5/28/2025 9:43,5/28/2025 11:52,100,7729,TRUE,5/28/2025 11:52,Extremely important,Extremely important,Extremely important,Extremely important,...,Very important,Very important,Extremely important,Extremely important,Extremely important,Very important,Very important,Not at this time.,Provide an update each year on the Augustin Co...,More events supporting staff and sharing best ...
19,5/28/2025 11:03,5/28/2025 11:03,4,32,FALSE,5/28/2025 15:03,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,5/29/2025 14:07,5/29/2025 14:07,4,5,FALSE,5/29/2025 18:07,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,5/29/2025 18:50,5/29/2025 18:57,100,438,TRUE,5/29/2025 18:57,Very important,Extremely important,Very important,Extremely important,...,Extremely important,Extremely important,Extremely important,Very important,Extremely important,Extremely important,Extremely important,NaN,NaN,NaN